const namespace = 'http://gams.uni-graz.at/viewer';
const xlink = 'http://www.w3.org/1999/xlink';
const status = document.querySelector('#status');
let viewer;
let activeUrls = [];
let revision = 0;

const languageText = value => typeof value === 'string' ? value : Object.values(value || {}).flat().join('; ');
const escapeText = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

function filename(reference) {
  if (!reference) throw new Error('An image reference is empty. Fill in every page reference.');
  try { return decodeURIComponent(new URL(reference, 'https://exercise.invalid/').pathname.split('/').pop()); }
  catch { throw new Error(`Cannot read image reference: ${reference}`); }
}

function readXml(text) {
  if (/<!DOCTYPE/i.test(text)) throw new Error('DOCTYPE declarations are not supported. Use the supplied XML template.');
  const doc = new DOMParser().parseFromString(text, 'application/xml');
  if (doc.querySelector('parsererror')) throw new Error('The XML is not well-formed. Check closing tags, nesting and quoted attributes.');
  const root = doc.documentElement;
  if (root.localName !== 'book' || root.namespaceURI !== namespace) throw new Error('Use the project XML template with the book root and viewer namespace.');
  const child = (parent, name) => Array.from(parent?.children || []).find(e => e.localName === name && e.namespaceURI === namespace);
  const value = name => child(root, name)?.textContent.trim() || '';
  const fields = [['author', 'Creator (as recorded)'], ['idno', 'Source repository identifier'], ['date', 'Date (as recorded)'], ['language', 'Language'], ['category', 'Document type'], ['languageCode', 'Language code'], ['source', 'Shelfmark']];
  const metadata = fields.filter(([key]) => value(key)).map(([key, label]) => ({ label, value: value(key) }));
  const owner = child(child(root, 'owner'), 'name')?.textContent.trim();
  if (owner) metadata.push({ label: 'Institution / website / rights (as recorded)', value: owner });
  const structure = child(root, 'structure');
  const pages = Array.from(structure?.children || []).filter(e => e.localName === 'div' && e.namespaceURI === namespace)
    .flatMap(div => Array.from(div.children).filter(e => e.localName === 'page' && e.namespaceURI === namespace))
    .map((page, index) => ({ reference: page.getAttributeNS(xlink, 'href'), label: `Page ${index + 1}` }));
  return { title: value('title'), metadata, pages, mode: 'XML' };
}

function readManifest(text) {
  let manifest;
  try { manifest = JSON.parse(text); } catch { throw new Error('The JSON cannot be read. Select the manifest generated by the Python script.'); }
  if (manifest.type !== 'Manifest' || !Array.isArray(manifest.items)) throw new Error('Use an IIIF Presentation 3 manifest generated by the exercise script.');
  const pages = manifest.items.map((canvas, index) => {
    const annotations = (canvas.items || []).flatMap(page => page.items || []);
    if (canvas.type !== 'Canvas' || annotations.length !== 1 || annotations[0].motivation !== 'painting' || annotations[0].body?.type !== 'Image') throw new Error(`Page ${index + 1}: this exercise supports one image per canvas. Use the supplied script.`);
    return { reference: annotations[0].body.id, label: languageText(canvas.label) || `Page ${index + 1}` };
  });
  return { title: languageText(manifest.label), metadata: (manifest.metadata || []).map(m => ({ label: languageText(m.label), value: languageText(m.value) })), pages, mode: 'IIIF manifest' };
}

async function imageSize(url, name) {
  const image = new Image();
  image.src = url;
  try { await image.decode(); } catch { throw new Error(`Cannot decode image: ${name}. Use a valid JPEG or PNG.`); }
  return { width: image.naturalWidth, height: image.naturalHeight };
}

async function showObject(model, files) {
  if (!model.title) throw new Error('Add a title to your metadata.');
  if (!model.pages.length) throw new Error('No page references found. Add pages using the supplied template.');
  if (model.pages.length > 200) throw new Error('Use no more than 200 pages for this teaching exercise.');
  const fileMap = new Map();
  for (const file of files) {
    if (fileMap.has(file.name)) throw new Error(`Duplicate filename: ${file.name}. Use unique image filenames.`);
    fileMap.set(file.name, file);
  }
  const urls = [];
  try {
    const base = new URL(`session/${++revision}/`, document.baseURI).href;
    const items = [];
    for (const [index, page] of model.pages.entries()) {
      const name = filename(page.reference);
      const file = fileMap.get(name);
      if (!file) throw new Error(`Missing image: ${name}. Select every referenced image, then open again.`);
      if (!/\.(jpe?g|png)$/i.test(name)) throw new Error(`Use JPEG or PNG images: ${name}`);
      const url = URL.createObjectURL(file);
      urls.push(url);
      const size = await imageSize(url, name);
      const body = { id: url, type: 'Image', format: /\.png$/i.test(name) ? 'image/png' : 'image/jpeg', ...size };
      const id = `${base}canvas/${index + 1}`;
      items.push({ id, type: 'Canvas', label: { none: [escapeText(page.label)] }, ...size, thumbnail: [{ ...body }], items: [{ id: `${base}page/${index + 1}`, type: 'AnnotationPage', items: [{ id: `${base}annotation/${index + 1}`, type: 'Annotation', motivation: 'painting', body, target: id }] }] });
    }
    const manifest = { '@context': 'http://iiif.io/api/presentation/3/context.json', id: `${base}manifest.json`, type: 'Manifest', label: { none: [escapeText(model.title)] }, metadata: model.metadata.map(m => ({ label: { none: [escapeText(m.label)] }, value: { none: [escapeText(m.value)] } })), items };
    await import('./vendor/mirador.min.js');
    document.querySelector('#result').hidden = false;
    if (!viewer) viewer = window.Mirador.viewer({ id: 'mirador', language: 'en', windows: [], window: { defaultSideBarPanel: 'info', sideBarOpenByDefault: true }, workspaceControlPanel: { enabled: false } });
    for (const id of Object.keys(viewer.store.getState().windows)) viewer.store.dispatch(window.Mirador.actions.removeWindow(id));
    for (const id of Object.keys(viewer.store.getState().manifests)) viewer.store.dispatch(window.Mirador.actions.removeManifest(id));
    viewer.store.dispatch(window.Mirador.actions.receiveManifest(manifest.id, manifest));
    viewer.store.dispatch(window.Mirador.actions.addWindow({ manifestId: manifest.id, thumbnailNavigationPosition: 'far-bottom' }));
    for (const url of activeUrls) URL.revokeObjectURL(url);
    activeUrls = urls;
    document.querySelector('#object-title').textContent = model.title;
    document.querySelector('#page-count').textContent = `${items.length} ${items.length === 1 ? 'page' : 'pages'}`;
    document.querySelector('#mapping').textContent = model.mode === 'XML' ? 'XML title → viewer title · Description fields → metadata · Page references → ordered images' : 'Your Python-generated manifest supplies the metadata and page order. Selected images are linked locally in this browser.';
    status.textContent = `Opened ${items.length} pages from ${model.mode}. Your files stay in this browser.`;
  } catch (error) {
    for (const url of urls) URL.revokeObjectURL(url);
    throw error;
  }
}

async function run(action) {
  status.classList.remove('error');
  status.textContent = 'Reading metadata and images…';
  const buttons = document.querySelectorAll('button');
  buttons.forEach(button => { button.disabled = true; });
  try { await action(); }
  catch (error) { status.textContent = error.message; status.classList.add('error'); }
  finally { buttons.forEach(button => { button.disabled = false; }); }
}

document.querySelector('#upload-form').addEventListener('submit', event => {
  event.preventDefault();
  run(async () => {
    const metadata = document.querySelector('#metadata').files[0];
    if (!metadata) throw new Error('Select your XML or manifest first.');
    const text = await metadata.text();
    const model = metadata.name.toLowerCase().endsWith('.xml') ? readXml(text) : readManifest(text);
    await showObject(model, document.querySelector('#images').files);
  });
});

document.querySelector('#demo').addEventListener('click', () => run(async () => {
  const response = await fetch('./metadata.xml');
  if (!response.ok) throw new Error('The example could not be loaded. Please reload the page.');
  const files = await Promise.all(['page-001.jpg', 'page-002.jpg'].map(async name => {
    const image = await fetch(`./images/${name}`);
    if (!image.ok) throw new Error(`Example image unavailable: ${name}`);
    return new File([await image.blob()], name, { type: 'image/jpeg' });
  }));
  await showObject(readXml(await response.text()), files);
}));
