/** Generate static course pages from the verified Google Drive resource list. */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const course = 'Summer School Musicology 2026 · Research Data Workflows and LLMs';
const drive = 'https://drive.google.com/drive/folders/1TaqB-BvNt20uAvOCCnQMQBk_2cV0gLjW';
const prep = 'https://docs.google.com/presentation/d/19zybf1mABP3qM65GXv0xEGVososbhM03P9_INInYPj8';
const data = 'https://drive.google.com/drive/folders/1Q5iiPsBfiaAWOK7Tuy9Z5LyiO0EUaZFJ';
const practice = 'https://drive.google.com/drive/folders/1KhFwP1L1iUO6PBKQZGP4p8rxU2vZSfG0';
const sessions = [
  { n:1, title:'Making Estate Materials Digitally Accessible', short:'Archival sources and research data', description:'Follow an archival object through digitisation, catalogue description and digital access, using Stefan Zweig Digital. Examine how metadata and file relationships shape what researchers can find and use.', slides:'1vMd2UfI9MydUEN6MMOYT0LZcJ6MYv2DmK9AQbyzJ7xc', notes:'1DU6UbE4xURFZ3fkPn7MD2loZ2naPysFYX1ypeI0D_Kg' },
  { n:2, title:'Large Language Models for Research Data Workflows: An Introduction', short:'Models, prompts and context', description:'Explore how large language models work and how prompt and context engineering support research tasks. Connect model behaviour to transcription, metadata and the checking of generated results.', slides:'1GUzZEVdCq2gRphzXIsnZ1Gg_4bGdqYy_aiwl8kErJUc', notes:'18DUWW5ju8R827mf7LNPU_zSoxd2R8WF8ienI8fCcFrM' },
  { n:3, title:'Large Language Models for Research Data Workflows: Hands-On Practice', short:'Transcription and information extraction', description:'Work with historical programme sources and examine the path from page images to transcriptions and structured statements. Retain evidence, distinguish roles and check the scope of each claim.', slides:'1IOCdHFnlxyNuMwiyUNviyQ53KwD13k4_tRXpieXHgOo', notes:'138Kl6CCtpZI3BM6VHGEgpFuZPVZJTfJT5FH8ASIdHPA' },
  { n:4, title:'Promptotyping with Research Data', short:'From research requirements to an application', description:'Use documented research requirements and reviewed data to develop a working prototype with an AI coding agent. Inspect the interface and its evidence links against concrete records.', slides:'1-fAKvaGBndVmzWcptltYqW1CXNYhQgji5W6JvIdChQ0', notes:'1U37su5SllKVdlEKKgwcqadwf7-4yNyOxpgbgSxsLYkc' },
];
const escape = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const link = (url,label,kind='') => `<a${kind ? ` class="${kind}"` : ''} href="${escape(url)}">${escape(label)}</a>`;
const slidesUrl = s => `https://docs.google.com/presentation/d/${s.slides}`;
const notesUrl = s => `https://docs.google.com/document/d/${s.notes}`;

function frame(title,content,base,current) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title === course ? course : `${title} · ${course}`)}</title><meta name="description" content="Slides, lecture notes, hands-on tools and downloads for Christopher Pollin's four sessions at Summer School Musicology 2026."><link rel="stylesheet" href="${base}assets/site.css"></head>
<body><a class="skip" href="#content">Skip to content</a><header class="site-header"><div class="wrap header-inner"><a class="brand" href="${base}index.html">Summer School Musicology 2026</a><nav aria-label="Main navigation"><a href="${base}index.html#sessions"${current==='sessions'?' aria-current="page"':''}>Sessions</a><a href="${base}materials/"${current==='materials'?' aria-current="page"':''}>Materials & downloads</a><a href="${base}tools/iiif-viewer/">IIIF viewer</a></nav></div></header><main class="wrap" id="content">${content}</main><footer><div class="wrap"><p>Christopher Pollin · <a href="https://dhcraft.org/">Digital Humanities Craft</a><br>Summer School “Gender – Knowledge – Mobility. Digital Perspectives in Musicology” · University of Music and Performing Arts Graz · 16–17 September 2026</p><p>Course website developed with GPT-6 Astra in Codex. The image tool uses the open-source Mirador viewer. <a href="https://github.com/chpollin/summer-school-musicology-2026">Source code</a></p></div></footer></body></html>`;
}

function resources(s,base) {
  if(s.n===1) return `<div class="panel"><h3>From XML to IIIF</h3><p>Combine your XML metadata and images, generate a manifest with Python, and inspect the result in Mirador. The viewer also accepts the XML directly.</p><div class="actions">${link(`${base}tools/iiif-viewer/`,'Open the IIIF viewer','button')}${link(`${base}downloads/xml-iiif-workshop.zip`,'Download Python + IIIF package','button secondary')}</div><p class="small">Contains the script, XML template, two synthetic example images and an English guide.</p></div><ul class="resources"><li>${link(`${base}downloads/pdf-to-images.zip`,'PDF to images · Python exercise package')}<br><span class="small">Script, two-page source PDF and instructions.</span></li><li>${link(data,'Source images and shared exercise files on Google Drive')}</li><li>${link('https://drive.google.com/file/d/1cH99vlIbUsL5BFODsBZcZEiLkkvoMSh4/view','Schulnachricht · source image')}</li></ul>`;
  if(s.n===2) return `<ul class="resources"><li>${link(`${prep}/preview`,'Technical preparation slides')}</li><li>${link(data,'Shared source material and exercise files')}</li></ul>`;
  if(s.n===3) return `<ul class="resources"><li>${link(practice,'Session 3 · exercise folders')}</li><li>${link('https://drive.google.com/drive/folders/1bS_F8yDOWWK89cLeFzj6nFxz9GBH18Qa','Hands-on 1 · Python in Visual Studio Code')}</li><li>${link('https://drive.google.com/drive/folders/1tbZvvloLe4gZ5IBe9gsqqQfiiScgbP3F','Hands-on 2 · AI Harness')}</li><li>${link(data,'Shared source material and exercise files')}</li></ul>`;
  return `<ul class="resources"><li>${link(drive,'Course material folder')}</li><li>${link(data,'Shared data and prototype materials')}</li><li>${link(`${base}tools/iiif-viewer/`,'Explore the course viewer as an example application')}</li></ul>`;
}

const home = `<div class="hero"><p class="eyebrow">Summer School Musicology 2026</p><h1>Research Data Workflows<br>and LLMs</h1><p class="lead">From archival sources to structured research data and applications. Slides, lecture notes and practical exercises for four sessions.</p><p class="byline">Christopher Pollin · Digital Humanities Craft · 16–17 September 2026</p><div class="actions">${link('#sessions','Explore the sessions','button')}${link('materials/','Materials & downloads','button secondary')}</div></div><section id="sessions"><div class="section-heading"><h2>Four sessions</h2><a href="${prep}/preview">Technical preparation</a></div><div class="grid">${sessions.map(s=>`<article class="card"><span class="number">SESSION ${s.n}</span><h3>${escape(s.title)}</h3><p>${escape(s.description)}</p><a class="card-link" href="sessions/session-${s.n}.html">Slides, lecture notes & exercises →</a></article>`).join('')}</div></section><section class="panel"><p class="eyebrow">Hands-on tool · Session 1</p><h2>See your metadata and images in Mirador</h2><p>Open your XML or Python-generated IIIF manifest alongside its page images. Inspect the title and page order, then change the input and compare the result.</p><div class="actions">${link('tools/iiif-viewer/','Open the IIIF viewer','button')}${link('downloads/xml-iiif-workshop.zip','Download the exercise package','button secondary')}</div></section>`;
await writeFile(path.join(root,'index.html'),frame(course,home,'','sessions'));

for(const s of sessions) {
  const content = `<div class="hero session"><p class="eyebrow">Session ${s.n} · ${escape(s.short)}</p><h1>${escape(s.title)}</h1><p class="lead">${escape(s.description)}</p><div class="actions">${link('#slides','Slides','button')}${link('#lecture-notes','Lecture notes','button secondary')}${link('#exercises','Exercises & files','button secondary')}</div></div><section id="slides"><h2>Slides</h2><div class="actions">${link(`${slidesUrl(s)}/preview`,'Open slides','button secondary')}${link(`${slidesUrl(s)}/export/pdf`,'Download PDF','button secondary')}${link(`${slidesUrl(s)}/export/pptx`,'Download PowerPoint','button secondary')}</div><iframe class="embed slides" src="${slidesUrl(s)}/embed?start=false&loop=false&delayms=3000" title="Session ${s.n} slides" allowfullscreen loading="lazy"></iframe></section><section id="lecture-notes"><h2>Lecture notes</h2><p>Read the explanations and exercises alongside the slides.</p><div class="actions">${link(`${notesUrl(s)}/preview`,'Open lecture notes','button secondary')}${link(`${notesUrl(s)}/export?format=pdf`,'Download PDF','button secondary')}${link(`${notesUrl(s)}/export?format=docx`,'Download Word','button secondary')}</div><details><summary>Read the lecture notes here</summary><iframe class="embed notes" src="${notesUrl(s)}/preview" title="Session ${s.n} lecture notes" loading="lazy"></iframe></details></section><section id="exercises"><h2>Exercises & files</h2>${resources(s,'../')}</section><div class="session-nav">${s.n>1?link(`session-${s.n-1}.html`,`← Session ${s.n-1}`):link('../index.html','← All sessions')}${s.n<4?link(`session-${s.n+1}.html`,`Session ${s.n+1} →`):link('../materials/','All materials →')}</div>`;
  await writeFile(path.join(root,'sessions',`session-${s.n}.html`),frame(`Session ${s.n} · ${s.title}`,content,'../','sessions'));
}

const materials = `<div class="hero session"><p class="eyebrow">Course resources</p><h1>Materials & downloads</h1><p class="lead">Slides and lecture notes for every session, together with the tools and files used in the exercises.</p><div class="actions">${link(drive,'Open the course folder','button secondary')}${link(`${prep}/preview`,'Technical preparation','button secondary')}</div></div><section><h2>Slides and lecture notes</h2>${sessions.map(s=>`<article class="resource"><p class="eyebrow">Session ${s.n}</p><h3>${link(`../sessions/session-${s.n}.html`,s.title)}</h3><div class="actions">${link(`${slidesUrl(s)}/preview`,'Slides','button secondary')}${link(`${slidesUrl(s)}/export/pdf`,'Slides PDF','button secondary')}${link(`${notesUrl(s)}/preview`,'Lecture notes','button secondary')}${link(`${notesUrl(s)}/export?format=pdf`,'Notes PDF','button secondary')}</div></article>`).join('')}</section><section><h2>Tools and exercise files</h2>${resources(sessions[0],'../')}<article class="resource"><h3>LLM hands-on practice</h3>${resources(sessions[2],'../')}</article><article class="resource"><h3>Promptotyping materials</h3>${resources(sessions[3],'../')}</article></section>`;
await writeFile(path.join(root,'materials','index.html'),frame('Materials & downloads',materials,'../','materials'));
console.log('Generated course homepage, four session pages and material overview.');
