/** Body of the IIIF viewer page; the element IDs are the contract with tools/iiif-viewer/app.js. */
export function viewerPage() {
  return `<div class="hero session">
<p class="eyebrow">Hands-on tool · Session 1</p>
<h1>From XML to IIIF</h1>
<p class="lead">Select your XML or generated IIIF manifest and its page images to see them as a digital object in Mirador. The files stay in your browser.</p>
</div>
<section class="controls" aria-label="Open your digital object">
<form id="upload-form">
<div class="inputs">
<label><span>1. Metadata</span><small>metadata.xml or manifest.json</small><input id="metadata" type="file" accept=".xml,.json,application/json,text/xml,application/xml" required></label>
<label><span>2. Page images</span><small>Select all referenced images together</small><input id="images" type="file" accept="image/jpeg,image/png,.jpg,.jpeg,.png" multiple required></label>
</div>
<div class="actions"><button type="submit" class="button">Open in Mirador</button><button id="demo" type="button" class="button secondary">Try the example</button></div>
</form>
<p id="status" role="status" aria-live="polite">Start with the example, or choose your own files above.</p>
</section>
<section id="result" hidden aria-label="Your object in Mirador">
<div class="result-heading"><h2 id="object-title">Your digital object</h2><p id="page-count"></p></div>
<p id="mapping" class="small"></p>
<div id="mirador"></div>
</section>
<section class="guide">
<details><summary>Try the transformation yourself</summary><p>Change the title or swap two page references in your XML. Save the file, select it again and open it in Mirador. Compare the metadata and page order.</p></details>
<details><summary>Generate the manifest with Python</summary><p><a href="../../downloads/xml-iiif-workshop.zip" download>Download the exercise package</a>, extract it and open the folder in your editor. With Python 3.11 or later installed, run:</p><pre><code>python -m pip install "lxml&gt;=5,&lt;7" "Pillow&gt;=10,&lt;13"
python build_manifest.py metadata.xml</code></pre><p>Then select the generated <code>manifest.json</code> and the images above. On macOS and Linux use <code>python3</code> if required.</p></details>
<details><summary>Which XML and manifests can I use?</summary><p>The <a href="metadata.xml" download>project XML template</a> and the IIIF Presentation 3 image manifests generated by the supplied Python script. Each <code>&lt;page xlink:href="images/page-001.jpg"/&gt;</code> must refer to a selected image with a unique filename, and the XML page order determines the viewer order. Remote images in manifests are not fetched, and reloading the page clears the object.</p></details>
</section>`;
}
